

'''
Random Module

Pseudorandom Number Generators
Computers are not random, because they are built with circuits and switches. But randomness is very important when building software, especially games. It would be really boring if every move in a video game was pre-determined.

So, some computer scientists invented pseudorandom number generators. e.g. https://en.wikipedia.org/wiki/Mersenne_Twister

If you want to learn more about pseudorandom number generators, I recommend watching this video by Khan Academy: https://www.youtube.com/watch?v=GtOt7EBNEwQ&ab_channel=KhanAcademyLabs

The Random module in Python
Read the docs here: https://docs.python.org/3/library/random.html

To use it you need to first import it:

import random

Random Whole Numbers Within a Range
import random
rand_num = random.randint(1, 10)

#This will produce a random whole number between 1 and 10 (inclusive).
Modules in Python
Python allows us to put code into different files and import that code if needed. This means that we can better organise and modularise our code.

You can create a new module simply by creating a new .py file, and then you can import variables or functions from that file just by using the import keyword.

Random Floats
You can generate a random number between 0.0 (inclusive) and 1.0 (not inclusive) using the following code from the random module:

import random
rand_num_0_to_1 = random.random()
It can also be represented like this

0.0 <= random.random() < 1.0

You can expand the range of random numbers generated by this method using multiplication.

e.g. random.random() * 5

Will generate a random number between 0 and 5.

Another way to generate random floating point numbers is to use the uniform() function.

import random
random_float = random.uniform(1, 10)
#This will generate a random floating point number between 1 and 10. 
This method may or may not include the upper bound depending on the rounding of the floating point number. So it's best represented as:

a <= random.uniform(a,b) <= b

So depending on if you want the upper bound included you will choose whether to use random.random() or random.uniform().

PAUSE 1 - Heads or Tails
Create a coin flip program using what you have learnt about randomisation in Python. It should randomly print "Heads" or "Tails" everytime it is run.

 Hint 
You'll need to think about what you have learnt about conditional statements in Python.

'''


import random
# import my_first_module
#
# random_integer = random.randint(1, 10)
# print(random_integer)
# print(my_first_module.my_number)

# random_number_0_to_1 = random.random() *1000000
# print(random_number_0_to_1)
#
# random_float = random.uniform(0.0, 100000000000)
# print(random_float)

random_integer = random.randint(1, 100)
print(random_integer)

if random_integer % 2 == 0:
    print("Heads")
else:
    print("Tails")


#Solution 
import random

random_integer = random.randint(1, 10)
print(random_integer)

random_number_0_to_1 = random.random() * 10
print(random_number_0_to_1)

random_float = random.uniform(1, 10)
print(random_float)

random_heads_or_tails = random.randint(0, 1)
if random_heads_or_tails == 0:
    print("Heads")
else:
    print("Tails")



'''
Lists

You can create a simple collection of ordered items using a Python list. e.g.

fruits = ["Cherry", "Apple", "Pear"]

or

states_of_america = ["Delaware", "Pennsylvania", "New Jersey", "Georgia", "Connecticut", "Massachusetts", "Maryland", "South Carolina", "New Hampshire", "Virginia", "New York", "North Carolina", "Rhode Island", "Vermont", "Kentucky", "Tennessee", "Ohio", "Louisiana", "Indiana", "Mississippi", "Illinois", "Alabama", "Maine", "Missouri", "Arkansas", "Michigan", "Florida", "Texas", "Iowa", "Wisconsin", "California", "Minnesota", "Oregon", "Kansas", "West Virginia", "Nevada", "Nebraska", "Colorado", "North Dakota", "South Dakota", "Montana", "Washington", "Idaho", "Wyoming", "Utah", "Oklahoma", "New Mexico", "Arizona", "Alaska", "Hawaii"]

Accessing Items in Lists
You can provide the name of the list then a square bracket and then the item index that you want. e.g.

states_of_america[0]

will give you "Delaware".

Remember that everything computer related, the first number we count with is 0 and never 1. 0, 1, 2, 3 instead of 1, 2, 3 4.

Negative Indices
You can access items in the list counting from the end of the list by using negative whole numbers. e.g.

fruits = ["Cherry", "Apple", "Pear"]
fruits[-1] #this will be "Pear"
Modifying Items
You can use the same syntax to get hold of items in a List to modify it. e.g.

fruits = ["Cherry", "Apple", "Pear"]
fruits[0] = "Orange"
# fruits will now become ["Orange", "Apple", "Pear"]
Adding Items
You can add items to the end of a List using the append() function. e.g.

fruits = ["Cherry", "Apple", "Pear"]
fruits.append("Orange")
# fruits will now become ["Cherry", "Apple", "Pear", "Orange"]
Lists Documentation
You can find the documentation for Python Lists and other List related functions here: https://docs.python.org/3/tutorial/datastructures.html

'''



US_States = ["Delaware", "Pennsylvania", "New Jersey", "Georgia",
             "Connecticut", "Massachusetts", "Maryland", "South Carolina",
             "New Hampshire", "Virginia", "New York", "North Carolina",
             "Rhode Island", "Vermont", "Kentucky", "Tennessee", "Ohio",
             "Louisiana", "Indiana", "Mississippi", "Illinois", "Alabama",
             "Maine", "Missouri", "Arkansas", "Michigan", "Florida", "Texas",
             "Iowa", "Wisconsin", "California", "Minnesota", "Oregon", "Kansas",
             "West Virginia", "Nevada", "Nebraska", "Colorado", "North Dakota",
             "South Dakota", "Montana", "Washington", "Idaho", "Wyoming", "Utah",
             "Oklahoma", "New Mexico", "Arizona", "Alaska", "Hawaii"]



US_States.extend(["Gowtam"])
print(US_States[-1])


#SOlution
states_of_america = ["Delaware", "Pennsylvania", "New Jersey", "Georgia", "Connecticut", "Massachusetts", "Maryland", "South Carolina", "New Hampshire", "Virginia", "New York", "North Carolina", "Rhode Island", "Vermont", "Kentucky", "Tennessee", "Ohio", "Louisiana", "Indiana", "Mississippi", "Illinois", "Alabama", "Maine", "Missouri", "Arkansas", "Michigan", "Florida", "Texas", "Iowa", "Wisconsin", "California", "Minnesota", "Oregon", "Kansas", "West Virginia", "Nevada", "Nebraska", "Colorado", "North Dakota", "South Dakota", "Montana", "Washington", "Idaho", "Wyoming", "Utah", "Oklahoma", "New Mexico", "Arizona", "Alaska", "Hawaii"]

states_of_america[1] = "Pencilvania"

states_of_america.append("Angelaland")

states_of_america.extend(["Angelaland", "Jack Bauer Land"])

print(states_of_america)



'''
Banker Roulette


Figure out how to pick a random name from the list of friends.

 Hint 1 
There are two ways of doing this and they are equally valid.
 Hint 2 
Think about how you can generate random number to use an index to pick out items from the List.
 Hint 3 
Alternatively think about using the documentation to figure out how to get a random item from a List in Python.
'''


import random

friends = ["Alice", "Bob", "Charlie", "David", "Emanuel"]

no = random.randint(0,4)
print(no)
print(friends[no])

#print(random.choice(friends))


#Solution
import random
friends = ["Alice", "Bob", "Charlie", "David", "Emanuel"]

# 1st Option
print(random.choice(friends))

# 2nd Option
random_index = random.randint(0, 4)
print(friends[random_index])



'''
Index Error 

Length of List
You can get the length of a list (number of items in the list) or the length of a string (number characters in the string) by using the len() function. https://docs.python.org/3/library/functions.html#len

IndexError
When you try to access an item that is not in the range of the List, you will get an IndexError. e.g.

fruits = ["Cherry", "Apple", "Pear"]
print(fruits[3]) #This will be an IndexError
Nested Lists
You can put Lists inside other Lists, this becomes something called a "Nested List" or a "2D List". e.g.

fruits = ["Cherry", "Apple", "Pear"]
veg = ["Cucumber", "Kale", "Spinnach"]
fruits_and_veg = [fruits, veg]
#The list would look like this: [["Cherry", "Apple", "Pear"], ["Cucumber", "Kale", "Spinnach"]]
You could also represent the list in 2D format like this:

["Cherry", "Apple", "Pear"]
["Cucumber", "Kale", "Spinnach"]

'''

# states_of_america = ["Delaware", "Pennsylvania", "New Jersey", "Georgia", "Connecticut", "Massachusetts", "Maryland",
#                      "South Carolina", "New Hampshire", "Virginia", "New York", "North Carolina", "Rhode Island",
#                      "Vermont", "Kentucky", "Tennessee", "Ohio", "Louisiana", "Indiana", "Mississippi", "Illinois",
#                      "Alabama", "Maine", "Missouri", "Arkansas", "Michigan", "Florida", "Texas", "Iowa", "Wisconsin",
#                      "California", "Minnesota", "Oregon", "Kansas", "West Virginia", "Nevada", "Nebraska", "Colorado",
#                      "North Dakota", "South Dakota", "Montana", "Washington", "Idaho", "Wyoming", "Utah", "Oklahoma",
#                      "New Mexico", "Arizona", "Alaska", "Hawaii"]
#
# No_of_states = len(states_of_america)
#
# print(states_of_america[No_of_states -1])


a = ["1", "2", "3", "4", "5", "6", "7", "8", "9"]
b = ["a", "b", "c", "d", "e", "f", "g", "h", "i"]

c = [a, b]
print(c[0][1])


#Solution

states_of_america = ["Delaware", "Pennsylvania", "New Jersey", "Georgia", "Connecticut", "Massachusetts", "Maryland",
                     "South Carolina", "New Hampshire", "Virginia", "New York", "North Carolina", "Rhode Island",
                     "Vermont", "Kentucky", "Tennessee", "Ohio", "Louisiana", "Indiana", "Mississippi", "Illinois",
                     "Alabama", "Maine", "Missouri", "Arkansas", "Michigan", "Florida", "Texas", "Iowa", "Wisconsin",
                     "California", "Minnesota", "Oregon", "Kansas", "West Virginia", "Nevada", "Nebraska", "Colorado",
                     "North Dakota", "South Dakota", "Montana", "Washington", "Idaho", "Wyoming", "Utah", "Oklahoma",
                     "New Mexico", "Arizona", "Alaska", "Hawaii"]

print(states_of_america[49])  # No error
print(states_of_america[50])  # IndexError

# Using len() to find the number of items in a List
num_states = len(states_of_america)
print(states_of_america[num_states - 1])


# dirty_dozen = ["Strawberries", "Spinach", "Kale", "Nectarines", "Apples", "Grapes", "Peaches", "Cherries", "Pears",
# "Tomatoes", "Celery", "Potatoes"]

fruits = ["Strawberries", "Nectarines", "Apples", "Grapes", "Peaches", "Cherries", "Pears"]
vegetables = ["Spinach", "Kale", "Tomatoes", "Celery", "Potatoes"]

dirty_dozen = [fruits, vegetables]
print(dirty_dozen)



'''
Rock Paper Scissors

You are going to build a Rock, Paper, Scissors game. You will need to use what you have learnt about randomisation and Lists to achieve this.

Demo
https://appbrewery.github.io/python-day4-demo/

'''

import random
rock = '''
    _______
---'   ____)
      (_____)
      (_____)
      (____)
---.__(___)
'''

paper = '''
    _______
---'   ____)____
          ______)
          _______)
         _______)
---.__________)
'''

scissors = '''
    _______
---'   ____)____
          ______)
       __________)
      (____)
---.__(___)
'''
game_images = [rock, paper, scissors]
human_response = input("Whats your choice? Rock, Paper or Scissors?")
a = ["Rock", "Paper", "Scissors"]
# c = random.randint(0,2)
# pc_response = a[c]

pc_response = random.choice(a)

if human_response == "Rock" and pc_response == "Paper":
    print(human_response)
    print(pc_response)
    print("PC wins")
if human_response == "Paper" and pc_response == "Rock":
    print(human_response)
    print(pc_response)
    print("You win")
if human_response == "Paper" and pc_response == "Scissors":
    print(human_response)
    print(pc_response)
    print("PC wins")
if human_response == "Scissors" and pc_response == "Paper":
    print(human_response)
    print(pc_response)
    print("You win")
if human_response == "Scissors" and pc_response == "Rock":
    print(human_response)
    print(pc_response)
    print("PC wins")
if human_response == "Rock" and pc_response == "Scissors":
    print(human_response)
    print(pc_response)
    print("You win")
if human_response == pc_response:
    print(human_response)
    print(pc_response)
    print("Game tied")

#Solution

import random

rock = '''
    _______
---'   ____)
      (_____)
      (_____)
      (____)
---.__(___)
'''

paper = '''
    _______
---'   ____)____
          ______)
          _______)
         _______)
---.__________)
'''

scissors = '''
    _______
---'   ____)____
          ______)
       __________)
      (____)
---.__(___)
'''

game_images = [rock, paper, scissors]

user_choice = int(input("What do you choose? Type 0 for Rock, 1 for Paper or 2 for Scissors.\n"))
# Note: it's worth checking if the user has made a valid choice before the next line of code.
# If the user typed somthing other than 0, 1 or 2 the next line will give you an error.
# You could for example write:
if user_choice >= 0 and user_choice <= 2:
    print(game_images[user_choice])

computer_choice = random.randint(0, 2)
print("Computer chose:")
print(game_images[computer_choice])

if user_choice >= 3 or user_choice < 0:
    print("You typed an invalid number. You lose!")
elif user_choice == 0 and computer_choice == 2:
    print("You win!")
elif computer_choice == 0 and user_choice == 2:
    print("You lose!")
elif computer_choice > user_choice:
    print("You lose!")
elif user_choice > computer_choice:
    print("You win!")
elif computer_choice == user_choice:
    print("It's a draw!")

